format_version: 10
pipelines:
  test-helloworld:
    group: rundmc
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      helloworld-github:
        git: https://github.com/luckytaxi/helloworld/
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test-unit:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - i am a unit test
                command: echo
                run_if: passed
